[book]
authors = ["gbaian10"]
language = "zh-Hant-TW"
multilingual = false
src = "src"
title = "rust_book"

[build]
create-missing = false

[preprocessor.pagetoc]
[output.html]
default-theme = "Rust"
preferred-dark-theme = "Rust"
additional-css = ["theme/pagetoc.css", "theme/whichlang.css", "devicon.css"]
additional-js  = ["theme/pagetoc.js", "theme/whichlang.js"]

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0
